name: Release
on:
  push:
    paths:
      - version
    branches:
      - master
jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6

      - name: Read the gem version
        uses: Strech/run-javascript-action@v0.3.0
        id: gem_version
        with:
          script: |
            return $.fs.readFileSync("./version")
      - name: Create a gem version tag
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ github.token }}
          script: |
            const version = ${{ steps.gem_version.outputs.result }};
            const ref = "refs/tags/v" + version;
            console.log(${{ steps.gem_version.outputs.result }})
            github.git.createRef({...context.repo, ref: ref, sha: "${{ github.sha }}"});
