name: Release
on:
  push:
    paths:
      - version
    branches:
      - master
jobs:
  create_release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Up Ruby
        uses: ruby/setup-ruby@ec106b438a1ff6ff109590de34ddc62c540232e0
        with:
          ruby-version: 2.6

      - name: Read the gem version
      uses: actions/javascript-action@v1
      id: gem_version
      with:
        script: |
          return $.fs.readFileSync("./version")
